public enum GameState {
    BLACK_PLAYER_CHOOSE_FIGURE,
    BLACK_PLAYER_MOVE_FIGURE,
    WHITE_PLAYER_CHOOSE_FIGURE,
    WHITE_PLAYER_MOVE_FIGURE,
    CHECK,
    BLACK_SAYS_CHECK, WHITE_SAYS_CHECK, PLAYER_MOVE_FIGURE, PLAYER_CHOOSE_FIGURE, CHECK_MATE
}
